package com.quickweather.exceptions;

import lombok.Getter;

@Getter
public enum UserErrorType {
    INVALID_FIRST_NAME,
    INVALID_LAST_NAME,
    INVALID_EMAIL,
    EMAIL_ALREADY_EXISTS,
    INVALID_PASSWORD,
    ACCOUNT_DISABLED,
    ACCOUNT_ENABLED,
    INVALID_PHONE_NUMBER,
    USER_NOT_FOUND,
    INVALID_CURRENT_PASSWORD,
    INVALID_NEW_PASSWORD,
    INVALID_REQUEST;
}
